### ISSUE TITLE
[Question] Any way to run a test, with pry?

### ISSUE THREAD

**Issue by dahernan** [d4l3k/go-pry#6]
For example if I need to run
```
go test -test.run="^TestRefreshToken$"
```
and put, in one of the test
```
pry.Pry()
```

**Comment by d4l3k** [comment]
Currently there isn't a way to do that but it's definitely on the roadmap.

go-pry has a rather simple model for running pry commands. It takes the provided file, and makes a copy of it with pry.Apply(<scope>) instead of the pry.Pry() statement.

The next step will be to make a backup of all the go files in the current directory and tweak the actual files, thus allowing standard go commands to run.

**Comment by dahernan** [comment]
Thank you, looks pretty good!

**Comment by d4l3k** [comment]
This should be working with the latest commits. go-pry is now just a wrapper around go so you can use all of the normal go commands.

For example:
```
go-pry test -test.run="^TestRefreshToken$"
```
